videos = [
    'https://www.youtube.com/watch?v=DZEzUC4QW54',
    'https://www.youtube.com/watch?v=PXwStduNw14',
    'https://www.youtube.com/watch?v=iBMfg4WkKL8',
    'https://www.youtube.com/watch?v=wtV5ev6813I',
    'https://www.youtube.com/watch?v=Tp25LmdYlds',
    'https://www.youtube.com/watch?v=8jPQjjsBbIc',
    'https://www.youtube.com/watch?v=qYvXk_bqlBk',
    'https://www.youtube.com/watch?v=F2hc2FLOdhI',
    'https://www.youtube.com/watch?v=wX78iKhInsc',
    'https://www.youtube.com/watch?v=arj7oStGLkU',
    'https://www.youtube.com/watch?v=LWULB9Aoopc',
    'https://www.youtube.com/watch?v=iG9CE55wbtY',
    'https://www.youtube.com/watch?v=XQJhRDbsDzI',
    'https://www.youtube.com/watch?v=XcIwN_uZy3c',
    'https://www.youtube.com/watch?v=kmIZeEu-3CY',
    'https://www.youtube.com/watch?v=B6rIUxHZ9f4',
    'https://www.youtube.com/watch?v=6Af6b_wyiwI',
    'https://www.youtube.com/watch?v=8KkKuTCFvzI',
    'https://www.youtube.com/watch?v=IlU-zDU6aQ0',
    'https://www.youtube.com/watch?v=5xL6eaiM14o',
    'https://www.youtube.com/watch?v=xYemnKEKx0c',
    'https://www.youtube.com/watch?v=CiyJSIUrbYE',
    'https://www.youtube.com/watch?v=_GM6z0vqVgE',
    'https://www.youtube.com/watch?v=dU5ymuzlf_g',
    'https://www.youtube.com/watch?v=I0TITV7I2sE',


]